image: nixos/nix:2.3.6

pipelines:
  default:
    - step:
        script:
          - nix-channel --add https://nixos.org/channels/nixpkgs-unstable nixpkgs
          - nix-channel --update
          - nix-build
