version: 2
jobs:
  build:
    docker:
      - image: nixos/nix:2.3.6
    steps:
      - checkout
      - run: nix-env -i wget
      # - run: nix-build
      - run: nix-shell --command "cabal update; cabal test --enable-tests --test-show-details=streaming; exit"
      - store_test_results:
          path: ./test-reports/**/*.xml
