name: learn-github-actions
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix-build
      - run: nix-shell --command "cabal test --test-show-details=streaming"
